name: "Docker Hub Images" 

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am UTC
  release:
    types: [ published ]
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: 'Version (eg. v2.5.0)'
        default: latest

jobs:
  registry:
    name: Publish to Registry
    uses: XNXKTech/workflows/.github/workflows/docker-build.yml@main
    with:
      registry: https://registry-1.docker.io/v2/
    secrets:
      username: ${{ secrets.DOCKER_HUB_USER}}
      password: ${{ secrets.DOCKER_HUB_PASSWORD}}
